Comment before binning to see what is going on

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -61,42 +61,42 @@ jobs:
         env:
           ACTIONS_STEP_DEBUG: true
 
-      - name: Create mock reads
-        shell: bash -leo pipefail {0}
-        run: bash workflow/scripts/generate_mock_data.sh
+      # - name: Create mock reads
+      #   shell: bash -leo pipefail {0}
+      #   run: bash workflow/scripts/generate_mock_data.sh
 
       - name: Clean conda cache
         run: conda clean --all --yes
 
-      - name: Test workflow - Preprocessing
-        uses: snakemake/snakemake-github-action@v1.24.0
-        with:
-          directory: .
-          snakefile: workflow/Snakefile
-          args: >
-            --use-conda
-            --show-failed-logs
-            --cores 3
-            --conda-cleanup-pkgs cache
-            --latency-wait 5
-            pre
+      # - name: Test workflow - Preprocessing
+      #   uses: snakemake/snakemake-github-action@v1.24.0
+      #   with:
+      #     directory: .
+      #     snakefile: workflow/Snakefile
+      #     args: >
+      #       --use-conda
+      #       --show-failed-logs
+      #       --cores 3
+      #       --conda-cleanup-pkgs cache
+      #       --latency-wait 5
+      #       pre
 
-      - name: Test workflow - Assemble
-        uses: snakemake/snakemake-github-action@v1.24.0
-        with:
-          directory: .
-          snakefile: workflow/Snakefile
-          args: >
-            --use-conda
-            --show-failed-logs
-            --cores 3
-            --conda-cleanup-pkgs cache
-            --latency-wait 5
-            assemble
+      # - name: Test workflow - Assemble
+      #   uses: snakemake/snakemake-github-action@v1.24.0
+      #   with:
+      #     directory: .
+      #     snakefile: workflow/Snakefile
+      #     args: >
+      #       --use-conda
+      #       --show-failed-logs
+      #       --cores 3
+      #       --conda-cleanup-pkgs cache
+      #       --latency-wait 5
+      #       assemble
 
 
       - name: Give to the binning steps an assembly that will work
-        shell: bash -leo pipefail {0}
+        # shell: bash -leo pipefail {0}
         run: >
           mkdir --parents results/assembly/renaming/ &&
           gzip -dc resources/mock_assembly.fa.gz > results/assembly/renaming/all.fa
