Back to running the pipeline with simple dataset, do the switcheroo on assembly, then run binning

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,58 +41,58 @@ jobs:
             ~/.cache/pre-commit/
           key: snakemake-conda-${{ env.CACHE_NUMBER }}
 
-      - name: Prepare micromamba
-        uses: mamba-org/setup-micromamba@v1
-        with:
-          init-shell: bash
-          environment-name: mock
-          create-args: >-
-            seqtk
-            pigz
-            samtools
-          cache-environment: true
-          post-cleanup: 'all'
-          condarc: |
-            channels:
-            - conda-forge
-            - bioconda
-            - defaults
-            channel_priority: strict
-        env:
-          ACTIONS_STEP_DEBUG: true
+      # - name: Prepare micromamba
+      #   uses: mamba-org/setup-micromamba@v1
+      #   with:
+      #     init-shell: bash
+      #     environment-name: mock
+      #     create-args: >-
+      #       seqtk
+      #       pigz
+      #       samtools
+      #     cache-environment: true
+      #     post-cleanup: 'all'
+      #     condarc: |
+      #       channels:
+      #       - conda-forge
+      #       - bioconda
+      #       - defaults
+      #       channel_priority: strict
+      #   env:
+      #     ACTIONS_STEP_DEBUG: true
 
-      - name: Create mock reads
-        shell: bash -leo pipefail {0}
-        run: bash workflow/scripts/generate_mock_data.sh
+      # - name: Create mock reads
+      #   shell: bash -leo pipefail {0}
+      #   run: bash workflow/scripts/generate_mock_data.sh
 
       - name: Clean conda cache
         run: conda clean --all --yes
 
-      # - name: Test workflow - Preprocessing
-      #   uses: snakemake/snakemake-github-action@v1.24.0
-      #   with:
-      #     directory: .
-      #     snakefile: workflow/Snakefile
-      #     args: >
-      #       --use-conda
-      #       --show-failed-logs
-      #       --cores 3
-      #       --conda-cleanup-pkgs cache
-      #       --latency-wait 5
-      #       pre
+      - name: Test workflow - Preprocessing
+        uses: snakemake/snakemake-github-action@v1.24.0
+        with:
+          directory: .
+          snakefile: workflow/Snakefile
+          args: >
+            --use-conda
+            --show-failed-logs
+            --cores 3
+            --conda-cleanup-pkgs cache
+            --latency-wait 5
+            pre
 
-      # - name: Test workflow - Assemble
-      #   uses: snakemake/snakemake-github-action@v1.24.0
-      #   with:
-      #     directory: .
-      #     snakefile: workflow/Snakefile
-      #     args: >
-      #       --use-conda
-      #       --show-failed-logs
-      #       --cores 3
-      #       --conda-cleanup-pkgs cache
-      #       --latency-wait 5
-      #       assemble
+      - name: Test workflow - Assemble
+        uses: snakemake/snakemake-github-action@v1.24.0
+        with:
+          directory: .
+          snakefile: workflow/Snakefile
+          args: >
+            --use-conda
+            --show-failed-logs
+            --cores 3
+            --conda-cleanup-pkgs cache
+            --latency-wait 5
+            assemble
 
 
       - name: Give to the binning steps an assembly that will work
